apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ include "pgadmin.password" . | quote }}
  pgpass: |
    {{ include "pgadmin.postgresHost" . }}:{{ .Values.postgres.port }}:*:{{ .Values.postgres.username }}:{{ include "pgadmin.postgresPassword" . }}
