{{- if and .Values.primary.persistence.enabled (not .Values.primary.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.fullname" . }}-data
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.primary.persistence.storageClass }}
  storageClassName: {{ .Values.primary.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.primary.persistence.size }}
{{- end }}
