apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  database: {{ .Values.auth.database | quote }}
  password: {{ include "postgresql.password" . | quote }}
