apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pocket-id.fullname" . }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  encryptionKey: {{ include "pocket-id.encryptionKey" . | quote }}
